### spring application properties

spring:
  application:
    name: reward-service

### application specific properties

welcome:
  message: Welcome to Reward Service !!

### server properties

server:
 port: 8100
 servlet:
    context-path: /reward-service

### Eureka server registration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}

### actuator properties

management:
  endpoints:
    web:
      exposure:
        include: "*"

### logging properties

logging:
  level:
    org.springframework: INFO
  file: reward-service.log
  pattern:
    console: "%d{yyyy-MM-dd} %d{HH:mm:ss.SSS} | %blue(%thread) | %5p | %logger | %m%n"
    file: "%d{yyyy-MM-dd} %d{HH:mm:ss.SSS} | %thread | %5p | %logger | %m%n"
