### spring application properties

spring:
  application:
    name: employee-service

### application specific properties
welcome:
  message: Welcome to Employee Service !!

### server properties

server:
  port: 8000
  servlet:
    context-path: /employee-service

### Feign properties

feign:
  httpclient:
    connection-timeout: 5000

### Eureka server registration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

### actuator properties

management:
  endpoints:
    web:
      exposure:
        include: "*"

### logging properties

logging:
  level:
    org.springframework: INFO
    com.pankiba.employeeservice.feign: DEBUG
    com.netflix.loadbalancer.DynamicServerListLoadBalancer: DEBUG
  file: employee-service.log
  pattern:
    console: "%d{yyyy-MM-dd} %d{HH:mm:ss.SSS} | %blue(%thread) | %5p | %logger | %m%n"
    file: "%d{yyyy-MM-dd} %d{HH:mm:ss.SSS} | %thread | %5p | %logger | %m%n"